# wrangler.toml at your repo root
name = "bpb-panel-1"
compatibility_date = "2025-06-18"

[vars]
UUID    = "ff17f8c5-0b1a-4f23-8870-69abce9f6ba1"
TR_PASS = "ywueE7@avp_|#2]I"
SUB_PATH= "wn1Dh@TKiRQEmmZG"
